sudo: false
language: sourcepawn

addons:
  apt_packages:
    - lib32stdc++6

matrix:
  allow_failures:
    - env: SMVERSION=1.10

env:
  - SMVERSION=1.9
  - SMVERSION=1.10

before_script:
  - mkdir temp
  - wget "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O temp/sourcemod-$SMVERSION-linux.tar.gz
  - tar -xzf temp/sourcemod-$SMVERSION-linux.tar.gz -C temp/
  - cp -r temp/addons/sourcemod/scripting/* scripting/
  - cd scripting/
  - chmod +x spcomp

script:
- ./compile.sh deathmatch.sp
- ./compile.sh deathmatch_loader.sp
